version: "3"
services:
  fast-api:
    build: .
    restart: always
    tty: true
    ports:
      - 8002:80
    volumes:
      - .:/app:ro
    environment:
      - PYTHON_ENV=$PYTHON_ENV
      - WEB_CONCURRENCY=1